"""Verify immutable installed source files; excludes generated bytecode and venv."""
import argparse
import hashlib
import json
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--package", required=True)
parser.add_argument("--runtime", required=True)
args = parser.parse_args()
manifest = json.loads((Path(args.package) / "MANIFEST.sha256.json").read_text())
expected = {name: sha for name, sha in manifest.items() if name.startswith("src/") or name == "requirements.lock.txt"}
runtime = Path(args.runtime)
for name, sha in expected.items():
    path = runtime / name
    if path.is_symlink() or not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != sha:
        parser.exit(1, "Installed runtime source integrity mismatch.\n")
for path in (runtime / "src").rglob("*.py"):
    if path.relative_to(runtime).as_posix() not in expected:
        parser.exit(1, "Unrecognized Python file in installed runtime.\n")
print("Runtime source verified.")
